### PR TITLE
make the pgc stuff look somewhat sane with updated layout. Fixes #64

### LINKED ISSUE #64: Layout with new gc.com topbar is goofy
screen shot 2017-09-10 at 21 35 28

### PR DESCRIPTION
**Pull request by sdahlbac**
After:

image

Known issue: 
- something like `#pgcUserMenuButton:focus, #pgcUserMenuButton:hover { color: #02874d; }` should be needed to have the arrow change color on focus/hover to avoid "polar bears in snow". However, can't get it to work right now :(

### CODE REVIEW

**Comment by magma1447** [comment]
Much appreciated that you want to solve this. I haven't even looked at it myself yet, though I have noticed the irritating issues.

I tried it in both Chrome and Firefox, and it didn't really work out, see attached screenshot. The "PGC-menu" gets quite broken. Also it's triggered by clicking the "GCCOM menu" as well. I haven't yet investigated why. Since I can see it works for you (your screenshot) I am a bit confused. I'll see if I get some time to look at it.

I tested with https://github.com/sdahlbac/greasemonkey-geocaching-projectgc/raw/a9a3155051415de603e90122e4bdff16bb29c90b/greasemonkey-geocaching-projectgc.user.js

screenshot_20170911_11 08 52_cfd

**Comment by magma1447** [comment]
While working on something else, I noticed that your patch works on a cache-page. Seems like the menu has to be generated differently depending on which page we are on. It was a bit like that before as well. In fact, it has always been a bit broken on some of their pages, but less broken than it is now.

**Comment by sdahlbac** [comment]
Ah, did not occur to me that it might behave differently on different pages :(

I'll see if I can gather the energy to get this fixed for reals in a new PR. 

By the way, how is one supposed to develop user scripts efficiently, so far I've been doing select all in my editor and paste into Greasemonkey, but that can't be the best way (or at least so I hope...)

**Comment by magma1447** [comment]
I knew it from experience. Have been fighting it before. Also I happened to test your patch on /, which is the search page, which didn't work. :)

If you didn't notice, I did accept your PR and added a few fixes for other pages after that. I did not get the settings page to work though, issue #66. I have not yet made a new version release, waiting a few days to see if someone else tests it and finds something that's worse than before.

I am using Firefox when developing the userscript, I then open Firefox's file where it has it stored. I am a linux user and it's stored in ~/.mozilla/firefox/<random key>/gm_scripts/<script name>/<js file>. The path can be seen in the script manager.

**Pull request merged**
