### PR TITLE
Create Version 2.3.16

### PR DESCRIPTION
**Pull request by rteitelman**
1. Fixes issue with the elevation units.  In this version the units are displayed according to the imperial units setting in project-gc, not the scripts settings.   Fixes are commented around lines 67, 188, 284, 357, and 690
2. The wording of some of the script settings menu  is cleaned up to be be more accurate.
3. The script settings menu is aligned further right so it should no longer be cut-off on the left.

### CODE REVIEW

**Comment by magma1447** [comment]
The pull request is for a new file. It needs to be a modification of the correct file, right now it's impossible to read the changes in the version control system.

**Comment by rteitelman** [comment]
I have no idea how to do this.  I can document the changes, but don't know the format to do so.  I was hoping someone who knows their away around github could do it.

**Comment by capoaira** [comment]
You need to edit the `greasemonkey-geocaching-projectgc.user.js`. Just copy your code into this file (your fork of course). Git version control shows all the changes you make, making it easier to review and test changes.

When I first started using Git, I had a few problems as well. I recommend working with a local copy of your fork using the "GitHub Desktop" client and watching a few tutorials to learn it. (Once you learn Git, you will enjoy working with it ;))

**Comment by rteitelman** [comment]
Well I did my best.  Very confusing.  I uploaded a file, and commited it , and made a pull request.  Is it visible and in the right place for review?

**Comment by jewettg** [comment]
working @rteitelman to get this working for him.

**Pull request closed without merging**
